add new Dockerfile for spark with new image Java + config the spark app + add new jars

diff --git a/src/spark/Dockerfile b/src/spark/Dockerfile
--- a/src/spark/Dockerfile
+++ b/src/spark/Dockerfile
@@ -1,32 +1,85 @@
-FROM python:3.12.1-bullseye
+FROM eclipse-temurin:17-jammy
 
-RUN apt-get update && apt-get install -y openjdk-11-jdk \
-    && apt-get clean \
-    && rm -rf /var/lib/apt/lists/*
+ARG spark_uid=185
 
-ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
-ENV PATH=$PATH:$JAVA_HOME/bin
+RUN groupadd --system --gid=${spark_uid} spark && \
+    useradd --system --uid=${spark_uid} --gid=spark spark
 
-RUN curl -SL https://archive.apache.org/dist/spark/spark-3.5.5/spark-3.5.5-bin-hadoop3.tgz -o spark-3.5.5-bin-hadoop3.tgz \
-    && tar -xzf spark-3.5.5-bin-hadoop3.tgz -C /opt/ \
-    && ln -s /opt/spark-3.5.5-bin-hadoop3 /opt/spark \
-    && rm spark-3.5.5-bin-hadoop3.tgz
+RUN set -ex; \
+    apt-get update; \
+    apt-get install -y gnupg2 wget bash tini libc6 libpam-modules krb5-user libnss3 procps net-tools gosu libnss-wrapper; \
+    mkdir -p /opt/spark; \
+    mkdir /opt/spark/python; \
+    mkdir -p /opt/spark/examples; \
+    mkdir -p /opt/spark/work-dir; \
+    chmod g+w /opt/spark/work-dir; \
+    touch /opt/spark/RELEASE; \
+    chown -R spark:spark /opt/spark; \
+    echo "auth required pam_wheel.so use_uid" >> /etc/pam.d/su; \
+    rm -rf /var/lib/apt/lists/*
+
+# Install Apache Spark
+# https://downloads.apache.org/spark/KEYS
+ENV SPARK_TGZ_URL=https://archive.apache.org/dist/spark/spark-3.5.5/spark-3.5.5-bin-hadoop3.tgz \
+    SPARK_TGZ_ASC_URL=https://archive.apache.org/dist/spark/spark-3.5.5/spark-3.5.5-bin-hadoop3.tgz.asc \
+    GPG_KEY=F28C9C925C188C35E345614DEDA00CE834F0FC5C
+
+RUN set -ex; \
+    export SPARK_TMP="$(mktemp -d)"; \
+    cd $SPARK_TMP; \
+    wget -nv -O spark.tgz "$SPARK_TGZ_URL"; \
+    wget -nv -O spark.tgz.asc "$SPARK_TGZ_ASC_URL"; \
+    export GNUPGHOME="$(mktemp -d)"; \
+    gpg --batch --keyserver hkps://keys.openpgp.org --recv-key "$GPG_KEY" || \
+    gpg --batch --keyserver hkps://keyserver.ubuntu.com --recv-keys "$GPG_KEY"; \
+    gpg --batch --verify spark.tgz.asc spark.tgz; \
+    gpgconf --kill all; \
+    rm -rf "$GNUPGHOME" spark.tgz.asc; \
+    \
+    tar -xf spark.tgz --strip-components=1; \
+    chown -R spark:spark .; \
+    mv jars /opt/spark/; \
+    mv RELEASE /opt/spark/; \
+    mv bin /opt/spark/; \
+    mv sbin /opt/spark/; \
+    mv kubernetes/dockerfiles/spark/decom.sh /opt/; \
+    mv examples /opt/spark/; \
+    ln -s "$(basename /opt/spark/examples/jars/spark-examples_*.jar)" /opt/spark/examples/jars/spark-examples.jar; \
+    mv kubernetes/tests /opt/spark/; \
+    mv data /opt/spark/; \
+    mv python/pyspark /opt/spark/python/pyspark/; \
+    mv python/lib /opt/spark/python/lib/; \
+    mv R /opt/spark/; \
+    chmod a+x /opt/decom.sh; \
+    cd ..; \
+    rm -rf "$SPARK_TMP";
+
+COPY ./spark /opt/spark
 
 ENV SPARK_HOME=/opt/spark
-ENV PATH=$PATH:$SPARK_HOME/bin
 
-RUN pip install --no-cache-dir pyspark==3.5.5
+WORKDIR /opt/spark
 
-RUN mkdir /app
+USER root
 
-RUN curl -SL https://jdbc.postgresql.org/download/postgresql-42.7.3.jar -o /app/postgresql-42.7.3.jar
-RUN curl -SL https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.5/spark-sql-kafka-0-10_2.12-3.5.5.jar -o /app/spark-sql-kafka-0-10_2.12-3.5.5.jar
-RUN curl -SL https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.5.2/kafka-clients-3.5.2.jar -o /app/kafka-clients-3.5.2.jar
-RUN curl -SL https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.5.5/spark-token-provider-kafka-0-10_2.12-3.5.5.jar -o /app/spark-token-provider-kafka-0-10_2.12-3.5.5.jar
-RUN curl -SL https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.12.0/commons-pool2-2.12.0.jar -o /app/commons-pool2-2.12.0.jar
+RUN set -ex; \
+    apt-get update; \
+    apt-get install -y python3 python3-pip; \
+    rm -rf /var/lib/apt/lists/*
 
-COPY ./spark/kafka_spark.py /app/
+RUN mkdir -p /opt/spark/jars && \
+    curl -SL https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.5/spark-sql-kafka-0-10_2.12-3.5.5.jar -o /opt/spark/jars/spark-sql-kafka-0-10_2.12-3.5.5.jar && \
+    curl -SL https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.5.5/spark-token-provider-kafka-0-10_2.12-3.5.5.jar -o /opt/spark/jars/spark-token-provider-kafka-0-10_2.12-3.5.5.jar && \
+    curl -SL https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.4.1/kafka-clients-3.4.1.jar -o /opt/spark/jars/kafka-clients-3.4.1.jar && \
+    curl -SL https://repo1.maven.org/maven2/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar -o /opt/spark/jars/lz4-java-1.8.0.jar && \
+    curl -SL https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.10.5/snappy-java-1.1.10.5.jar -o /opt/spark/jars/snappy-java-1.1.10.5.jar && \
+    curl -SL https://repo1.maven.org/maven2/org/slf4j/slf4j-api/2.0.7/slf4j-api-2.0.7.jar -o /opt/spark/jars/slf4j-api-2.0.7.jar && \
+    curl -SL https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-runtime/3.3.4/hadoop-client-runtime-3.3.4.jar -o /opt/spark/jars/hadoop-client-runtime-3.3.4.jar && \
+    curl -SL https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-api/3.3.4/hadoop-client-api-3.3.4.jar -o /opt/spark/jars/hadoop-client-api-3.3.4.jar && \
+    curl -SL https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar -o /opt/spark/jars/commons-logging-1.1.3.jar && \
+    curl -SL https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar -o /opt/spark/jars/jsr305-3.0.0.jar && \
+    curl -SL https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.1/commons-pool2-2.11.1.jar -o /opt/spark/jars/commons-pool2-2.11.1.jar
 
-WORKDIR /app
+USER spark
 
-#CMD ["/opt/spark/bin/spark-submit", "--jars", "/app/spark-sql-kafka-0-10_2.12-3.5.5.jar,/app/kafka-clients-3.5.2.jar,/app/spark-token-provider-kafka-0-10_2.12-3.5.5.jar", "/app/kafka_spark.py"]
+ENTRYPOINT [ "/opt/spark/entrypoint.sh" ]
